version: "3.8"
services:
  server:
    build:
      context: ./apps/server
    env_file:
      - ./apps/server/.env
    ports:
      - "3000:3456"
    # depends_on:
    #   - db
    networks:
      - app_network

  web:
    build:
      context: ./apps/web
    env_file:
      - ./apps/web/.env
    ports:
      - "3001:3457"
    depends_on:
      - server
    networks:
      - app_network

#   db:
#     image: postgres:15
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: hydro
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data
#     networks:
#       - app_network

# volumes:
#   db_data:

